# Generated by Django 4.2.11 on 2024-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals_natrium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(default='C:\\Users\\rlawl\\Desktop\\Capstone\\BigsasimiServer/static/avatar/default-avatar.png'),
        ),
    ]
