# Generated by Django 4.2.11 on 2024-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_goals_natrium_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(default='/static/avatar/default-avatar.png'),
        ),
    ]
