# Generated by Django 4.2.11 on 2024-05-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals_saccharide',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
