# Generated by Django 4.2.11 on 2024-05-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritioninformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestioninformation',
            name='saccharide',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
