# Generated by Django 4.2.11 on 2024-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritioninformation', '0002_ingestioninformation_saccharide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestioninformation',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='carb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='natrium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='saccharide',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='trans_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ingestioninformation',
            name='unsaturated_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
